### ISSUE TITLE
if user clicks on type button in property page than he should be redirected to all type of properties page

### ISSUE THREAD

**Issue by aayushchugh** [shriproperty/shriproperty#94]
![Screenshot 2022-04-21 203621](https://user-images.githubusercontent.com/69336518/164488463-40886d3b-1ee0-4343-99cd-08a77e24b75d.png)

eg: - if I click on Sale button than i should be able to see all the propeties those are for sale

**Comment by Arpitchugh** [comment]
solved and code pushed
